// @vitest-environment node
/// <reference types="node" />
// ---------------------------------------------------------------------------
// The totem reference page (app/public/totem-reference.html) is a static
// artifact generated by scripts/generate-totem-reference.mjs, which duplicates
// the effect labels/formatting from data.ts + utils.ts. These tests compare
// the generated page against the app's real formatTotemEffect output, so they
// fail whenever totem data or labels change without a regeneration.
// ---------------------------------------------------------------------------

import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { TOTEM_TIER_NAMES, totemsData } from '../data';
import { formatTotemEffect } from '../utils';

const html = readFileSync(
  new URL('../../public/totem-reference.html', import.meta.url),
  'utf8'
);

describe('generated totem reference page', () => {
  it('lists every totem with its blurb and exact effect lines', () => {
    for (const t of totemsData) {
      expect(html, `name of ${t.key}`).toContain(t.name);
      if (t.blurb) expect(html, `blurb of ${t.key}`).toContain(t.blurb);
      for (const e of t.effects) {
        expect(html, `effect line of ${t.key}`).toContain(formatTotemEffect(e));
      }
    }
  });

  it('has a header for every tier that contains cards', () => {
    for (const tier of new Set(totemsData.map(t => t.tier))) {
      expect(html).toContain(`Tier ${tier} \u2014 ${TOTEM_TIER_NAMES[tier]}`);
    }
  });
});
